export interface FoodItem {
  name: string
  calories: number
  serving: string
}

export const FOOD_DATABASE: FoodItem[] = [
  // ── Bread & Grains ──────────────────────────────────────────────────────────
  { name: 'Wheat Bread', calories: 80, serving: '1 slice (30g)' },
  { name: 'White Bread', calories: 75, serving: '1 slice (28g)' },
  { name: 'Sourdough Bread', calories: 90, serving: '1 slice (35g)' },
  { name: 'Bagel (plain)', calories: 245, serving: '1 medium (98g)' },
  { name: 'English Muffin', calories: 130, serving: '1 muffin (57g)' },
  { name: 'Flour Tortilla (large)', calories: 210, serving: '1 large (10")' },
  { name: 'Flour Tortilla (small)', calories: 90, serving: '1 small (6")' },
  { name: 'Corn Tortilla', calories: 60, serving: '1 tortilla (26g)' },
  { name: 'Pita Bread', calories: 165, serving: '1 pita (6")' },
  { name: 'Naan', calories: 260, serving: '1 piece (90g)' },
  { name: 'Croissant', calories: 275, serving: '1 croissant (67g)' },
  { name: 'Pancake', calories: 175, serving: '2 medium (6")' },
  { name: 'Waffle', calories: 185, serving: '1 waffle (75g)' },
  { name: 'White Rice (cooked)', calories: 206, serving: '1 cup (186g)' },
  { name: 'Brown Rice (cooked)', calories: 216, serving: '1 cup (195g)' },
  { name: 'Pasta (cooked)', calories: 220, serving: '1 cup (140g)' },
  { name: 'Spaghetti (cooked)', calories: 220, serving: '1 cup (140g)' },
  { name: 'Mac & Cheese (Kraft)', calories: 350, serving: '1 cup prepared' },
  { name: 'Oatmeal (cooked)', calories: 150, serving: '1 cup (234g)' },
  { name: 'Overnight Oats', calories: 200, serving: '1 cup' },
  { name: 'Granola', calories: 250, serving: '1/2 cup (61g)' },
  { name: 'Corn Flakes', calories: 100, serving: '1 cup (28g)' },
  { name: 'Cheerios', calories: 100, serving: '1 cup (28g)' },
  { name: 'Honey Bunches of Oats', calories: 150, serving: '3/4 cup (30g)' },
  { name: 'Crackers (saltine)', calories: 70, serving: '5 crackers (15g)' },
  { name: 'Graham Crackers', calories: 130, serving: '2 full sheets (28g)' },
  { name: 'Blueberry Muffin', calories: 340, serving: '1 large muffin' },

  // ── Proteins – Poultry ───────────────────────────────────────────────────────
  { name: 'Chicken Breast (cooked)', calories: 165, serving: '3 oz (85g)' },
  { name: 'Chicken Thigh (cooked)', calories: 209, serving: '3 oz (85g)' },
  { name: 'Chicken Drumstick', calories: 172, serving: '1 drumstick (77g)' },
  { name: 'Ground Turkey (cooked)', calories: 165, serving: '3 oz (85g)' },
  { name: 'Turkey Breast (deli)', calories: 60, serving: '2 oz (56g)' },
  { name: 'Rotisserie Chicken', calories: 190, serving: '3 oz (85g)' },

  // ── Proteins – Beef & Pork ───────────────────────────────────────────────────
  { name: 'Ground Beef 80/20 (cooked)', calories: 215, serving: '3 oz (85g)' },
  { name: 'Ground Beef 93/7 (cooked)', calories: 164, serving: '3 oz (85g)' },
  { name: 'Sirloin Steak (cooked)', calories: 207, serving: '3 oz (85g)' },
  { name: 'Ribeye Steak (cooked)', calories: 248, serving: '3 oz (85g)' },
  { name: 'Pork Chop (cooked)', calories: 187, serving: '3 oz (85g)' },
  { name: 'Pulled Pork', calories: 205, serving: '3 oz (85g)' },
  { name: 'Bacon', calories: 130, serving: '2 slices (16g cooked)' },
  { name: 'Ham (deli)', calories: 70, serving: '2 oz (56g)' },
  { name: 'Hot Dog', calories: 150, serving: '1 frank (45g)' },
  { name: 'Sausage Link (pork)', calories: 170, serving: '2 links (56g)' },
  { name: 'Italian Sausage', calories: 230, serving: '1 link (85g)' },
  { name: 'Pepperoni', calories: 140, serving: '1 oz (28g)' },

  // ── Proteins – Seafood ───────────────────────────────────────────────────────
  { name: 'Tuna (canned in water)', calories: 100, serving: '3 oz (85g)' },
  { name: 'Tuna (canned in oil)', calories: 170, serving: '3 oz (85g)' },
  { name: 'Salmon (cooked)', calories: 175, serving: '3 oz (85g)' },
  { name: 'Tilapia (cooked)', calories: 110, serving: '3 oz (85g)' },
  { name: 'Shrimp (cooked)', calories: 84, serving: '3 oz (85g)' },
  { name: 'Sardines (canned)', calories: 150, serving: '3 oz (85g)' },
  { name: 'Cod (cooked)', calories: 90, serving: '3 oz (85g)' },

  // ── Eggs & Dairy ─────────────────────────────────────────────────────────────
  { name: 'Egg (large)', calories: 72, serving: '1 egg (50g)' },
  { name: 'Egg White', calories: 17, serving: '1 white (33g)' },
  { name: 'Scrambled Eggs', calories: 200, serving: '2 eggs cooked' },
  { name: 'Hard Boiled Egg', calories: 78, serving: '1 egg' },
  { name: 'Whole Milk', calories: 149, serving: '1 cup (244ml)' },
  { name: '2% Milk', calories: 122, serving: '1 cup (244ml)' },
  { name: 'Skim Milk', calories: 83, serving: '1 cup (244ml)' },
  { name: 'Almond Milk (unsweetened)', calories: 30, serving: '1 cup (244ml)' },
  { name: 'Oat Milk', calories: 120, serving: '1 cup (244ml)' },
  { name: 'Greek Yogurt (plain, nonfat)', calories: 100, serving: '6 oz (170g)' },
  { name: 'Greek Yogurt (whole milk)', calories: 150, serving: '6 oz (170g)' },
  { name: 'Vanilla Yogurt', calories: 150, serving: '6 oz (170g)' },
  { name: 'Cheddar Cheese', calories: 115, serving: '1 oz (28g)' },
  { name: 'Mozzarella Cheese', calories: 85, serving: '1 oz (28g)' },
  { name: 'Parmesan Cheese (grated)', calories: 110, serving: '1 oz (28g)' },
  { name: 'American Cheese Slice', calories: 65, serving: '1 slice (19g)' },
  { name: 'Swiss Cheese', calories: 108, serving: '1 oz (28g)' },
  { name: 'Cream Cheese', calories: 100, serving: '2 tbsp (28g)' },
  { name: 'Cottage Cheese (2%)', calories: 110, serving: '1/2 cup (113g)' },
  { name: 'Butter', calories: 100, serving: '1 tbsp (14g)' },
  { name: 'Heavy Cream', calories: 52, serving: '1 tbsp (15ml)' },
  { name: 'Sour Cream', calories: 60, serving: '2 tbsp (30g)' },
  { name: 'String Cheese', calories: 80, serving: '1 stick (28g)' },

  // ── Nuts, Seeds & Legumes ────────────────────────────────────────────────────
  { name: 'Peanut Butter', calories: 190, serving: '2 tbsp (32g)' },
  { name: 'Almond Butter', calories: 196, serving: '2 tbsp (32g)' },
  { name: 'Almonds', calories: 164, serving: '1 oz / 23 nuts (28g)' },
  { name: 'Walnuts', calories: 185, serving: '1 oz (28g)' },
  { name: 'Cashews', calories: 157, serving: '1 oz (28g)' },
  { name: 'Peanuts', calories: 166, serving: '1 oz (28g)' },
  { name: 'Pistachios', calories: 160, serving: '1 oz / 49 nuts (28g)' },
  { name: 'Sunflower Seeds', calories: 165, serving: '1 oz (28g)' },
  { name: 'Chia Seeds', calories: 138, serving: '1 oz (28g)' },
  { name: 'Black Beans (cooked)', calories: 227, serving: '1 cup (172g)' },
  { name: 'Kidney Beans (cooked)', calories: 225, serving: '1 cup (177g)' },
  { name: 'Chickpeas (cooked)', calories: 269, serving: '1 cup (164g)' },
  { name: 'Lentils (cooked)', calories: 230, serving: '1 cup (198g)' },
  { name: 'Edamame (shelled)', calories: 188, serving: '1 cup (155g)' },
  { name: 'Hummus', calories: 70, serving: '2 tbsp (30g)' },
  { name: 'Refried Beans', calories: 237, serving: '1 cup (260g)' },

  // ── Vegetables ───────────────────────────────────────────────────────────────
  { name: 'Broccoli (cooked)', calories: 55, serving: '1 cup (156g)' },
  { name: 'Spinach (raw)', calories: 7, serving: '1 cup (30g)' },
  { name: 'Kale (raw)', calories: 33, serving: '1 cup (67g)' },
  { name: 'Romaine Lettuce', calories: 15, serving: '1 cup (47g)' },
  { name: 'Baby Carrots', calories: 35, serving: '10 carrots (85g)' },
  { name: 'Cucumber', calories: 16, serving: '1 cup sliced (119g)' },
  { name: 'Bell Pepper (red)', calories: 31, serving: '1 medium (119g)' },
  { name: 'Tomato', calories: 22, serving: '1 medium (123g)' },
  { name: 'Cherry Tomatoes', calories: 27, serving: '1 cup (149g)' },
  { name: 'Corn (cooked)', calories: 132, serving: '1 cup (154g)' },
  { name: 'Peas (cooked)', calories: 117, serving: '1 cup (160g)' },
  { name: 'Green Beans', calories: 44, serving: '1 cup (125g)' },
  { name: 'Potato (baked)', calories: 161, serving: '1 medium (173g)' },
  { name: 'Sweet Potato (baked)', calories: 103, serving: '1 medium (114g)' },
  { name: 'Avocado', calories: 240, serving: '1 medium (150g)' },
  { name: 'Avocado (half)', calories: 120, serving: '1/2 avocado (75g)' },
  { name: 'Onion', calories: 44, serving: '1 medium (110g)' },
  { name: 'Mushrooms (raw)', calories: 15, serving: '1 cup (70g)' },
  { name: 'Celery', calories: 10, serving: '2 stalks (80g)' },
  { name: 'Asparagus', calories: 27, serving: '1 cup (134g)' },
  { name: 'Zucchini', calories: 20, serving: '1 cup (113g)' },
  { name: 'Cauliflower', calories: 25, serving: '1 cup (100g)' },

  // ── Fruits ───────────────────────────────────────────────────────────────────
  { name: 'Apple', calories: 95, serving: '1 medium (182g)' },
  { name: 'Banana', calories: 105, serving: '1 medium (118g)' },
  { name: 'Orange', calories: 62, serving: '1 medium (131g)' },
  { name: 'Grapes', calories: 104, serving: '1 cup (151g)' },
  { name: 'Strawberries', calories: 49, serving: '1 cup (152g)' },
  { name: 'Blueberries', calories: 84, serving: '1 cup (148g)' },
  { name: 'Raspberries', calories: 64, serving: '1 cup (123g)' },
  { name: 'Mango', calories: 202, serving: '1 cup (165g)' },
  { name: 'Pineapple', calories: 82, serving: '1 cup chunks (165g)' },
  { name: 'Watermelon', calories: 46, serving: '1 cup diced (152g)' },
  { name: 'Peach', calories: 59, serving: '1 medium (150g)' },
  { name: 'Pear', calories: 101, serving: '1 medium (178g)' },
  { name: 'Grapefruit', calories: 52, serving: '1/2 fruit (123g)' },
  { name: 'Cherries', calories: 87, serving: '1 cup (138g)' },
  { name: 'Kiwi', calories: 42, serving: '1 medium (76g)' },

  // ── Condiments & Oils ────────────────────────────────────────────────────────
  { name: 'Olive Oil', calories: 119, serving: '1 tbsp (14g)' },
  { name: 'Vegetable Oil', calories: 120, serving: '1 tbsp (14g)' },
  { name: 'Coconut Oil', calories: 121, serving: '1 tbsp (14g)' },
  { name: 'Mayonnaise', calories: 90, serving: '1 tbsp (14g)' },
  { name: 'Ketchup', calories: 20, serving: '1 tbsp (17g)' },
  { name: 'Mustard (yellow)', calories: 5, serving: '1 tsp (5g)' },
  { name: 'Ranch Dressing', calories: 145, serving: '2 tbsp (30ml)' },
  { name: 'Italian Dressing', calories: 70, serving: '2 tbsp (30ml)' },
  { name: 'Caesar Dressing', calories: 160, serving: '2 tbsp (30ml)' },
  { name: 'Salsa', calories: 10, serving: '2 tbsp (30g)' },
  { name: 'Guacamole', calories: 45, serving: '2 tbsp (30g)' },
  { name: 'Soy Sauce', calories: 10, serving: '1 tbsp (16ml)' },
  { name: 'Hot Sauce', calories: 5, serving: '1 tsp' },
  { name: 'Maple Syrup', calories: 52, serving: '1 tbsp (20ml)' },
  { name: 'Honey', calories: 64, serving: '1 tbsp (21g)' },
  { name: 'Sugar (white)', calories: 49, serving: '1 tbsp (12g)' },
  { name: 'BBQ Sauce', calories: 70, serving: '2 tbsp (36g)' },
  { name: 'Sriracha', calories: 10, serving: '1 tsp (6g)' },

  // ── Snacks ───────────────────────────────────────────────────────────────────
  { name: 'Potato Chips', calories: 155, serving: '1 oz (28g)' },
  { name: 'Tortilla Chips', calories: 142, serving: '1 oz (28g)' },
  { name: 'Popcorn (air-popped)', calories: 30, serving: '1 cup (8g)' },
  { name: 'Pretzels', calories: 110, serving: '1 oz (28g)' },
  { name: 'Rice Cake', calories: 35, serving: '1 cake (9g)' },
  { name: 'Granola Bar', calories: 190, serving: '1 bar (47g)' },
  { name: 'Protein Bar (generic)', calories: 200, serving: '1 bar (60g)' },
  { name: 'Trail Mix', calories: 175, serving: '1/4 cup (40g)' },
  { name: 'Beef Jerky', calories: 80, serving: '1 oz (28g)' },
  { name: 'Cheese Crackers (Goldfish)', calories: 140, serving: '55 pieces (30g)' },

  // ── Sweets & Desserts ─────────────────────────────────────────────────────────
  { name: 'Dark Chocolate', calories: 170, serving: '1 oz (28g)' },
  { name: 'Milk Chocolate', calories: 153, serving: '1 oz (28g)' },
  { name: 'Ice Cream (vanilla)', calories: 145, serving: '1/2 cup (66g)' },
  { name: 'Chocolate Chip Cookie', calories: 148, serving: '1 large cookie' },
  { name: 'Brownie', calories: 130, serving: '1 piece (34g)' },
  { name: 'Glazed Donut', calories: 254, serving: '1 donut (60g)' },
  { name: 'Cheesecake', calories: 400, serving: '1 slice (125g)' },

  // ── Beverages ─────────────────────────────────────────────────────────────────
  { name: 'Orange Juice', calories: 112, serving: '8 oz (240ml)' },
  { name: 'Apple Juice', calories: 114, serving: '8 oz (240ml)' },
  { name: 'Cola Soda', calories: 140, serving: '12 oz (355ml)' },
  { name: 'Diet Soda', calories: 0, serving: '12 oz (355ml)' },
  { name: 'Sports Drink (Gatorade)', calories: 140, serving: '20 oz (591ml)' },
  { name: 'Coffee (black)', calories: 2, serving: '8 oz (240ml)' },
  { name: 'Latte (whole milk)', calories: 190, serving: '16 oz (480ml)' },
  { name: 'Cappuccino', calories: 120, serving: '12 oz (360ml)' },
  { name: 'Protein Shake (mixed)', calories: 150, serving: '1 scoop + water' },
  { name: 'Chocolate Milk', calories: 190, serving: '1 cup (240ml)' },
  { name: 'Beer (regular)', calories: 153, serving: '12 oz (355ml)' },
  { name: 'Wine (red)', calories: 125, serving: '5 oz (148ml)' },
  { name: 'Wine (white)', calories: 120, serving: '5 oz (148ml)' },

  // ── Common Meals & Fast Food ──────────────────────────────────────────────────
  { name: 'Pizza (cheese slice)', calories: 285, serving: '1 slice (107g)' },
  { name: 'Pizza (pepperoni slice)', calories: 310, serving: '1 slice (113g)' },
  { name: 'Cheeseburger', calories: 535, serving: '1 burger' },
  { name: 'Hamburger (plain)', calories: 420, serving: '1 burger' },
  { name: 'Chicken Sandwich', calories: 440, serving: '1 sandwich' },
  { name: 'French Fries (medium)', calories: 365, serving: '4 oz (113g)' },
  { name: 'Chicken Nuggets', calories: 280, serving: '6 pieces' },
  { name: 'Burrito (bean & cheese)', calories: 490, serving: '1 burrito' },
  { name: 'Beef Taco', calories: 210, serving: '1 taco' },
  { name: 'Quesadilla (cheese)', calories: 430, serving: '1 quesadilla' },
  { name: 'Pasta with Marinara', calories: 330, serving: '1 cup (250g)' },
  { name: 'Spaghetti & Meatballs', calories: 500, serving: '1 cup + 3 meatballs' },
  { name: 'Caesar Salad', calories: 250, serving: '2 cups with dressing' },
  { name: 'BLT Sandwich', calories: 430, serving: '1 sandwich' },
  { name: 'PB&J Sandwich', calories: 380, serving: '1 sandwich' },
  { name: 'Grilled Cheese Sandwich', calories: 390, serving: '1 sandwich' },
  { name: 'Fried Egg Sandwich', calories: 340, serving: '1 sandwich' },
  { name: 'Bowl of Cereal with Milk', calories: 250, serving: '1 cup cereal + 1/2 cup milk' },
  { name: 'Subway Footlong Turkey', calories: 560, serving: '1 footlong' },
  { name: 'Chipotle Burrito Bowl', calories: 730, serving: '1 bowl (est.)' },
]

export function searchFoods(query: string): FoodItem[] {
  if (!query.trim()) return []
  const q = query.toLowerCase()
  return FOOD_DATABASE
    .filter(f => f.name.toLowerCase().includes(q))
    .slice(0, 8)
}
